name: Oliver Peiss
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5841973514761776
title: yo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.05084291542880237
  lightness: 0.8471308103762567
  saturation: 0.6271164112258703
  rhythmicContrast: 0.9490547077730298
purpose: []
